### PR TITLE
exports pg connection from module

### PR DESCRIPTION
**Pull request by roryc89**
Allows pg connection to be accessed without hapi request.

### CODE REVIEW

**Comment by nelsonic** [comment]
Hi @roryc89 as discussed, would be good to include some detail in the Readme as to the _use-case_ for this change/addition. Also would you mind updating the `devDependencies` to latest versions and bumping the version of the package in `package.json` to reflect this backward-compatible feature enhancement? (_thanks!_)

**Comment by roryc89** [comment]
@nelsonic Sure thing! I'll update the PR.

**Comment by roryc89** [comment]
@nelsonic The PR has been updated.

**Comment by nelsonic** [comment]
_Superb_! 🌟 
Thanks again @roryc89!

**Comment by nelsonic** [comment]
@roryc89 new version on NPM: `hapi-postgres-connection@6.1.0` 👍

**Pull request merged**
